### PR TITLE
Adding Features Back

### PR DESCRIPTION
**Pull request by WyattBlue**
It's now possible to set a silent threshold and frame margin again. I also added argparse, printed how long the program took to finish at the end and the the new file will automatically open.

### CODE REVIEW

**Review by WyattBlue — COMMENTED** [review]
Frame Margin now added

**Comment by gusals3587** [comment]
Stop putting bunch of commits into one PR, one feature/fix should equal ONE PR, if I want to merge this, I need to check EVERY commit and make sure all of them doesn't have problems. If you want to implement a fix and merge it, make a brach for each fix you want on your fork, implement them, and then make a PR. You're adding silent_threshold, frame_margin, typo fix, prettifying code into this thing, all of them should be on different PR

**Comment by ming0520** [comment]
can you provide email of some communication way? I have something to discuss with you guys.

**Comment by WyattBlue** [comment]
I no longer feel like this fork is a good fit for this project anymore. That's why I'm closing this pull request.

**Pull request closed without merging**
